import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"
[window]
padding = { x = 2, y = 2}
opacity = 0.5
blur = true
[font]
normal = { family = "IoSevkaTerm Nerd Font", style = "Regular"}
[scrolling]
history = 10240
multiplier = 3
